# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Welcome to Liu Lab!
# Description of the Site
description: Explore RNA's mysteries in health and disease
# URL of Image of the Site
site-image: /assets/images/meta.jpg
# Keywords of the Site
site-keywords: Liu Lab, RNA, m6A, epigenetics, transcription, Peking University, 刘君实验室, RNA修饰, 表观遗传
# URL for the Image of custom Favicon
favicon-url: /assets/images/logo/logo_64_64_white.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/heroimage.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: junliu1223@pku.edu.cn
facebook_username: /
twitter_username: /
instagram_username: /
linkedin_username: /
github_username:  /
youtube_channel_id: /
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: /

# Disqus
disqus-shortname: /

# Name of the Author
author-name: Liu Lab
# URL for the Image of the Author
author-image: /assets/images/logo/logo_64_64_white.png
# 60 Words About the Author
author-about: 刘君实验室隶属于北京大学生命科学学院和北大-清华生命科学联合中心，致力于RNA表观转录组学与染色质生物学交叉领域的前沿研究。实验室以RNA修饰（m6A、假尿苷等）为核心，系统探究染色质RNA修饰调控基因组转录和着丝粒稳定性的分子机制，以及RNA修饰在胚胎发育、干细胞命运决定、肿瘤免疫和衰老中的生物学功能。
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://scholar.google.com/citations?hl=en&user=ktNYEi8AAAAJ

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  members:
    output: true  # 生成独立页面
    permalink: /members/:name/  # 自定义URL格式